export default [
    {
        title: 'Login Page || Shop',
        component: 'Login',
        path: '/login',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Register Page || Shop',
        component: 'Register',
        path: '/register',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Home Page || Shop',
        component: 'Home',
        path: '/',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Active email Page || Shop',
        component: 'ActiveEmail',
        path: '/user/activate/:activation_token',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Edit Profile Page || Shop',
        component: 'EditProfile',
        path: '/edit_user/:id',
        isProtected: true,
        exact: true,
    },
    {
        title: 'Profile Page || Shop',
        component: 'Profile',
        path: '/profile',
        isProtected: true,
        exact: true,
    },
    {
        title: 'Forgot Password Page || Shop',
        component: 'ForgotPassword',
        path: '/forgot',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Reset Password Page || Shop',
        component: 'ResetPassword',
        path: '/user/reset/:token',
        isProtected: false,
        exact: true,
    },
    {
        title: 'Products Page || Shop',
        component: 'Products',
        path: '/products',
        isProtected: false,
        exact: true,
    },
]
